name: tiler_example
version: 1.0.0
publish_to: 'none'

environment:
  sdk: ">=2.2.1-dev.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tiler:
    path: ../

flutter:
  assets:
    - assets/
