targets:
  $default:
    builders:
      json_serializable:
        options:
          checked: true
          create_factory: true
          create_to_json: false
          disallow_unrecognized_keys: true
          use_wrappers: true
