name: tiler
version: 0.0.1-dev
description: Library for rendering maps created with the Tiled map editor in Dart/Flutter.
author: Danny Tuppeny <danny@tuppeny.com>
repository: https://github.com/DanTup/tiler

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  path:
  json_serializable:

dev_dependencies:
  build_runner:
  test:
