name: tiler
version: 2.0.0
description: Library for rendering maps created with the Tiled map editor in Dart/Flutter.
# author: Danny Tuppeny <danny@tuppeny.com>
repository: https://github.com/DanTup/tiler

environment:
  sdk: ">=2.18.0-0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection:
  json_annotation: ^4.7.0
  path: ^1.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:
