name: tiler
version: 0.1.0
description: Library for rendering maps created with the Tiled map editor in Dart/Flutter.
author: Danny Tuppeny <danny@tuppeny.com>
repository: https://github.com/DanTup/tiler

environment:
  sdk: ">=2.2.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  json_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable:
  build_runner:
