name: Run Tests

on:
  push:
  pull_request:
  schedule:
     - cron: '0 6 * * 1-5'

jobs:

  build:

    name: "${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macOS-latest]

    steps:

      - uses: actions/checkout@v3

      # upload-artifact fails if the path does not exist (it only supports
      # silent failure for no-files-found, but the path must exist).
      - run: mkdir -p test/failures
        shell: pwsh

      - name: Setup Flutter
        uses: DanTup/gh-actions/setup-flutter@v1.1.0
        with:
          channel: master

      - name: Print Flutter version
        run: flutter --version

      - name: flutter pub get
        run: flutter pub get

      - name: flutter test
        run: flutter test

      - name: Store golden failures
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: golden-failures-${{ matrix.os }}
          path: test/failures
